// Copyright 2016 - 2023 The excelize Authors. All rights reserved. Use of
// this source code is governed by a BSD-style license that can be found in
// the LICENSE file.
//
// Package excelize providing a set of functions that allow you to write to
// and read from XLSX / XLSM / XLTM / XLTX files. Supports reading and
// writing spreadsheet documents generated by Microsoft Excel™ 2007 and later.
// Supports complex components by high compatibility, and provided streaming
// API for generating or reading data from a worksheet with huge amounts of
// data. This library needs Go version 1.18 or later.

package excelize

import (
	"archive/zip"
	"bytes"
	"fmt"
	"io"
	"os"
)

// File defines the populated spreadsheet file struct.
type File struct {
	options          *Options
	contentTypes     *xlsxTypes
	sheetCount       int
	appXML           *xlsxProperties
	coreXML          *xlsxDcTerms
	docPropsCustom   *xlsxCustomProperties
	sharedStringsMap map[string]int
	sharedStrings    *xlsxSST
	styles           *xlsxStyleSheet
	workBook         *xlsxWorkbook
	workSheets       map[string]*xlsxWorksheet
	zip              *zip.ReadCloser
	Pkg              sync.Map
	Charsets         map[string]string
	Path             string
	TempDir          string
}

// Options defines the options for opening and reading the spreadsheet.
type Options struct {
	Password          string
	RawCellValue      bool
	UnzipSizeLimit    int64
	UnzipXMLSizeLimit int64
	ShortDatePattern  string
	LongDatePattern   string
	LongTimePattern   string
	CultureInfo       CultureName
}

// NewFile provides a function to create a new file by default template.
// The newly created workbook will by default contain a worksheet named
// "Sheet1". For example:
//
//		f := excelize.NewFile()
//		defer func() {
//		    if err := f.Close(); err != nil {
//		        fmt.Println(err)
//		    }
//		}()
func NewFile(opts ...Options) *File {
	f := newFile()
	f.options = parseOptions(opts...)
	f.NewSheet("Sheet1")
	return f
}

// newFile is a helper that returns a pointer to a new File struct with
// initialized internal fields.
func newFile() *File {
	return &File{
		sharedStringsMap: make(map[string]int),
		workSheets:       make(map[string]*xlsxWorksheet),
		Charsets:         make(map[string]string),
	}
}

// parseOptions normalizes the options provided by the caller.
func parseOptions(opts ...Options) *Options {
	if len(opts) == 0 {
		return &Options{}
	}
	return &opts[0]
}

// Save provides a function to override the spreadsheet with the origin path.
func (f *File) Save(opts ...Options) error {
	if f.Path == "" {
		return ErrSave
	}
	return f.SaveAs(f.Path, opts...)
}

// SaveAs provides a function to create or update a spreadsheet at the
// provided path.
func (f *File) SaveAs(name string, opts ...Options) error {
	if len(name) > MaxFileNameLength {
		return ErrMaxFileNameLength
	}
	file, err := os.OpenFile(name, os.O_WRONLY|os.O_TRUNC|os.O_CREATE, 0o600)
	if err != nil {
		return err
	}
	defer file.Close()
	return f.Write(file, opts...)
}

// Write provides a function to write to an io.Writer.
func (f *File) Write(w io.Writer, opts ...Options) error {
	_, err := f.WriteTo(w, opts...)
	return err
}

// WriteTo implements io.WriterTo to write the file.
func (f *File) WriteTo(w io.Writer, opts ...Options) (int64, error) {
	if len(opts) > 0 {
		f.options = &opts[0]
	}
	buf, err := f.WriteToBuffer()
	if err != nil {
		return 0, err
	}
	return buf.WriteTo(w)
}

// WriteToBuffer provides a function to get bytes.Buffer from the saved file.
func (f *File) WriteToBuffer() (*bytes.Buffer, error) {
	buf := new(bytes.Buffer)
	zw := zip.NewWriter(buf)
	if err := f.writeToZip(zw); err != nil {
		_ = zw.Close()
		return buf, err
	}
	return buf, zw.Close()
}

// Close closes and cleans up the temporary directory for the open spreadsheet.
func (f *File) Close() error {
	if f.TempDir == "" {
		return nil
	}
	if f.zip != nil {
		if err := f.zip.Close(); err != nil {
			return err
		}
	}
	return os.RemoveAll(f.TempDir)
}

// Err returns the first non-nil error that was encountered.
func (f *File) Err() error {
	return nil
}

// writeToZip writes all workbook parts into the provided zip writer.
func (f *File) writeToZip(zw *zip.Writer) error {
	var err error
	f.Pkg.Range(func(k, v interface{}) bool {
		var fw io.Writer
		fw, err = zw.Create(fmt.Sprintf("%s", k))
		if err != nil {
			return false
		}
		_, err = fw.Write(v.([]byte))
		return err == nil
	})
	return err
}
